# Generated by Django 4.2.4 on 2023-11-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_historialusuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialusuario',
            name='email_anterior',
            field=models.EmailField(default='hola@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialusuario',
            name='role_anterior',
            field=models.CharField(default='usuario', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialusuario',
            name='username_anterior',
            field=models.CharField(default='usuario', max_length=150),
            preserve_default=False,
        ),
    ]
