# Generated by Django 4.2.4 on 2023-10-26 03:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('familiar', 'Familiar'), ('usuario', 'Usuario')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDestino', models.CharField(max_length=50)),
                ('latitudInicial', models.CharField(max_length=20)),
                ('longitudInicial', models.CharField(max_length=20)),
                ('latitudDestino', models.CharField(max_length=20)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(max_length=75)),
                ('alergias', models.TextField(max_length=75)),
                ('afecciones', models.TextField(max_length=75)),
                ('medicamento', models.TextField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id_sesiones', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('horaInicio', models.CharField(max_length=10)),
                ('fechaCierre', models.DateField()),
                ('horaCierre', models.CharField(max_length=10)),
                ('dispositivoInicio', models.CharField(max_length=50)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoTiempoReal',
            fields=[
                ('id_seguimiento_tiempo_real', models.AutoField(primary_key=True, serialize=False)),
                ('latitudActual', models.CharField(max_length=20)),
                ('longitudActual', models.CharField(max_length=20)),
                ('fecharegistro', models.DateField()),
                ('horaregistro', models.CharField(max_length=10)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('horaInicio', models.CharField(max_length=10)),
                ('detalleRuta', models.TextField()),
                ('iddestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.destino')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividades',
            fields=[
                ('id_registro_actividades', models.AutoField(primary_key=True, serialize=False)),
                ('fechaActual', models.DateField()),
                ('horaActividad', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id_preferencias', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=20)),
                ('volumen', models.IntegerField()),
                ('velocidadLectura', models.IntegerField()),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.TextField(max_length=75)),
                ('tiempodeviaje', models.TextField(max_length=75)),
                ('ruta', models.TextField(max_length=75)),
                ('descripcion', models.TextField(max_length=75)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesVoz',
            fields=[
                ('id_opciones_voz', models.AutoField(primary_key=True, serialize=False)),
                ('nombreVoz', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRuta',
            fields=[
                ('id_historial_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('horaInicio', models.CharField(max_length=10)),
                ('fechaTermino', models.DateField()),
                ('horaTermino', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('iddestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.destino')),
                ('idruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ruta')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinosFrecuentes',
            fields=[
                ('id_destinos_frecuentes', models.AutoField(primary_key=True, serialize=False)),
                ('iddestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.destino')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_contacto_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('parentesco', models.CharField(max_length=50)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CambioContraseña',
            fields=[
                ('id_cambio_contraseña', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCambio', models.DateField()),
                ('horaCambio', models.CharField(max_length=10)),
                ('contraseñaAnterior', models.CharField(max_length=50)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alertas', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAlerta', models.DateField()),
                ('horaAlerta', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipoAlerta', models.CharField(max_length=50)),
                ('ubicacionAlerta', models.CharField(max_length=50)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
