# Generated by Django 4.2.4 on 2023-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEliminado',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('familiar', 'Familiar'), ('usuario', 'Usuario'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('familiar', 'Familiar'), ('usuario', 'Usuario'), ('admin', 'Admin')], max_length=10),
        ),
    ]
