# Generated by Django 4.2.4 on 2023-11-19 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usuarioeliminado_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUsuario',
            fields=[
                ('id_historial_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('familiar', 'Familiar'), ('usuario', 'Usuario'), ('admin', 'Admin')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
