# Generated by Django 4.2.4 on 2023-11-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_historialusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialusuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historialusuario',
            name='role',
        ),
        migrations.RemoveField(
            model_name='historialusuario',
            name='username',
        ),
    ]
